[package]
name = "mystifine/myslib"
version = "0.2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]

include = [
  "src",
  "src/**",
  "default.project.json",
  "README.md",
  "wally.toml"
]